on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Package NuGet

jobs:
  get-version:
    runs-on: ubuntu-latest
    env:
      VERSION: "0.0.0"

    steps:
      - uses: actions/checkout@v1

      - name: Create Release NuGet package
        run: |
          arrTag=(${GITHUB_REF//\// })
          VERSION="${arrTag[2]}"
          VERSION="${VERSION//v}"
          echo "::set-env name=VERSION::${VERSION}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.5

      - name: Nuget Add Source
        run: nuget sources Add -Name "uxav" -Source https://nuget.pkg.github.com/uxav/index.json -username uxav -password ${{ secrets.GITHUB_TOKEN }} -StorePasswordInClearText

      - name: Pack Nuget
        run: nuget pack Package.nuspec -Version ${{ env.VERSION }}

      - name: Push generated package to GitHub registry
        run: nuget push *.nupkg -source "uxav"

