on:
  release:
    types: [published]

name: Package NuGet

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.5

      - name: Pack Nuget
        run: |
          version=${{ github.event.release.tag_name }}
          nuget pack Package.nuspec -Version ${version//v/}
